config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root 'businesses#index'

  get 'search' => 'businesses#search'

  resources :businesses do
    resources :coupons, shallow: true
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
# frozen_string_literal: true

class Business < ApplicationRecord
  has_one_attached :logo
  has_many :coupons, dependent: :delete_all

  validates :name, :street_1, presence: true, uniqueness: true
  validates :phone, numericality: { only_integer: true }, presence: true, uniqueness: true, case_sensitive: false
  validates :city, :state, :zip, presence: true
  validates :zip, numericality: { only_integer: true }, presence: true

  scope :search, lambda { |search_param|
    raise ArgumentError if search_param.blank?

    where('LOWER(name) LIKE ?', "%#{search_param.downcase}%").order(:name)
  }
end

app/models/coupon.rb
# frozen_string_literal: true

require 'barby/barcode/code_128'
require 'barby/outputter/svg_outputter'

class Coupon < ApplicationRecord
  belongs_to :business

  def barcode_svg
    if code.blank?
      'no barcode available'
    else
      Barby::Code128B.new(code).to_svg.html_safe
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
# frozen_string_literal: true

class BusinessesController < ApplicationController
  before_action :authenticate_admin!, only: %w[new create edit update destroy]
  before_action :set_business, only: %w[show edit update destroy]

  def index
    @businesses = Business.order(:name)
  end

  def new
    @business = Business.new
  end

  def create
    business = Business.create!(business_params)
    flash[:success] = 'Business added.'
    redirect_to business_path(business)
  rescue StandardError => e
    flash[:danger] = e
    redirect_to new_business_path
  end

  def show
    @coupons = @business.coupons
  end

  def edit; end

  def update
    @business.update!(business_params)
    flash[:success] = 'Business updated.'
    redirect_to business_path(@business)
  rescue StandardError => e
    flash[:danger] = e
    redirect_to edit_business_path
  end

  def destroy
    if @business.destroy
      flash[:success] = 'Business deleted.'
      redirect_to businesses_path
    else
      redirect_to edit_business_path
    end
  end

  def search
    @businesses = Business.search(search_param)
    render :index
  rescue ArgumentError
    flash[:success] = 'No results found.'
    redirect_to businesses_path
  end

  private

  def set_business
    @business = Business.find(params.require(:id))
  end

  def search_param
    params[:q]
  end

  def business_params
    params.require(:business).permit(
      :name,
      :street_1,
      :street_2,
      :city,
      :state,
      :zip,
      :phone,
      :logo
    )
  end
end

app/controllers/coupons_controller.rb
# frozen_string_literal: true

class CouponsController < ApplicationController
  before_action :authenticate_admin!, only: %w[create edit update destroy]
  before_action :set_coupon, only: %w[show edit update]

  def index; end

  def new
    @coupon = Coupon.new(business_id: params.require(:business_id))
  end

  def create
    coupon = Coupon.create!(coupon_params)
    flash[:success] = 'Coupon Saved.'
    redirect_to business_path(coupon.business)
  rescue StandardError => e
    flash[:danger] = e
    redirect_to new_business_coupon_path(coupon.business)
  end

  def show; end

  def edit; end

  def update
    @coupon.update!(coupon_params)
    flash[:success] = 'Coupon Updated.'
    redirect_to coupon_path(@coupon)
  rescue StandardError => e
    flash[:danger] = e
    redirect_to new_business_coupon_path(@coupon.business)
  end

  def destroy; end

  private

  def coupon_params
    params.require(:coupon).permit(
      :name,
      :description,
      :start_date,
      :end_date,
      :business_id,
      :code
    )
  end

  def set_coupon
    @coupon = Coupon.find(params.require(:id))
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/businesses_helper.rb
# frozen_string_literal: true

module BusinessesHelper
end

app/helpers/coupons_helper.rb
# frozen_string_literal: true

module CouponsHelper
end

app/views/businesses/_business.html.erb
<div class="form-group">
  <%= label_tag(:name, 'Name') %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= label_tag(:street_1, 'Address 1') %>
  <%= f.text_field :street_1, class: 'form-control' %>
</div>

<div class="form-group">
  <%= label_tag(:street_2, 'Address 2') %>
  <%= f.text_field :street_2, class: 'form-control' %>
</div>

<div class="form-group">
  <%= label_tag(:city, 'City') %>
  <%= f.text_field :city, class: 'form-control' %>
</div>

<div class="form-group">
  <%= label_tag(:state, 'State') %>
  <%= f.text_field :state, class: 'form-control' %>
</div>

<div class="form-group">
  <%= label_tag(:zip, 'Zipcode') %>
  <%= f.text_field :zip, class: 'form-control', type: :number %>
</div>

<div class="form-group">
  <%= label_tag(:phone, 'Phone Number') %>
  <%= f.text_field :phone, class: 'form-control', type: :tel %>
</div>

<div class="form-group">
  <%= label_tag(:logo, 'Logo') %>
  <% if @business.logo.attached? %>
    <%= image_tag @business.logo, class: 'rounded mx-auto d-block img-thumbnail' %>
  <% end %>
  <%= f.file_field :logo, accept: 'image/png,image/gif,image/jpeg' %>
</div>

app/views/businesses/destroy.html.erb
<h1>Businesses#destroy</h1>
<p>Find me in app/views/businesses/destroy.html.erb</p>

app/views/businesses/edit.html.erb
<%= form_with model: @business do |form| %>
  <%= render partial: 'business', locals: { f: form } %>

  <%= form.submit 'Update Business', class: 'btn btn-northcenter' %>
  <%= link_to "Delete Business", business_path(@business), method: :delete, data: { confirm: "You sure?" } %>
<% end %>

app/views/businesses/index.html.erb
<% @businesses.each do |business| %>
  <% if business.logo.attached? %>
    <div class="card business-index-card">
      <%= link_to business_path(business) do %>
        <%= image_tag business.logo, class: 'img-fluid img-thumbnail', alt: "#{business.name} logo" %>
      <% end %>
    </div>
  <% else %>
    <%= link_to business_path(business) do %>
      <div class="card business-index-card">
          <div class="card-body">
            <%= link_to business.name, business_path(business), class: 'card-text' %>
          </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/businesses/new.html.erb
<%= form_with model: @business do |form| %>
  <%= render partial: 'business', locals: { f: form } %>

  <%= form.submit 'Add Business', class: 'btn btn-northcenter' %>
<% end %>

app/views/businesses/show.html.erb
<% if current_admin %>
  <p class="float-right"><%= link_to '+ add a coupon', new_business_coupon_path(@business) %></p>
<% end %>

<% if @business.logo.attached? %>
  <%= image_tag @business.logo, class: 'rounded mx-auto d-block img-thumbnail' %>
<% end %>
<h2><%= @business.name %></h2>

<% if current_admin %>
  <%= link_to 'Edit', edit_business_path(@business) %>
<% end %>

<% @coupons.each do |coupon| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= coupon.name %></h5>
      <p class="card-text"><%= coupon.description %></p>
      <%= link_to 'Use Coupon', coupon_path(coupon), class: 'btn btn-northcenter' %>
    </div>
  </div>
<% end %>

app/views/coupons/_coupon.html.erb
<div class="form-group">
  <%= label_tag(:name, 'Name') %>
  <%= f.text_field :name, class: 'form-control', placeholder: '$5 Off!', required: true %>
  <small id="nameHelp" class="form-text text-muted">Enter the featured coupon text</small>
</div>

<div class="form-group">
  <%= label_tag(:description, 'Description') %>
  <%= f.text_field :description, class: 'form-control', required: true %>
  <small id="descriptionHelp" class="form-text text-muted">Enter a more detailed description</small>
</div>

<div class="form-group">
  <%= label_tag(:start_date, 'Start Date') %>
  <%= f.date_field :start_date, class: 'form-control', required: true %>
  <small id="startDateHelp" class="form-text text-muted">When does the promotion start?</small>
</div>

<div class="form-group">
  <%= label_tag(:end_date, 'End Date') %>
  <%= f.date_field :end_date, class: 'form-control', required: true %>
  <small id="startDateHelp" class="form-text text-muted">When does the promotion end?</small>
</div>

<div class="form-group">
  <%= label_tag(:code, 'Code') %>
  <%= f.text_field :code, class: 'form-control' %>
  <small id="codeHelp" class="form-text text-muted">Code will be used to generate a bar code.</small>
</div>

app/views/coupons/destroy.html.erb
<h1>Coupons#destroy</h1>
<p>Find me in app/views/coupons/destroy.html.erb</p>

app/views/coupons/edit.html.erb
<h2>Edit coupon for <%= @coupon.business.name %></h2>
<%= form_with model: @coupon, url: "/coupons/#{@coupon.id}", method: :patch do |form| %>
  <%= render partial: 'coupon', locals: { f: form } %>

  <%= form.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/coupons/index.html.erb
<h1>Coupons#index</h1>
<p>Find me in app/views/coupons/index.html.erb</p>

app/views/coupons/new.html.erb
<h2>Add a coupon for <%= @coupon.business.name %></h2>
<%= form_with model: @coupon, url: business_coupons_path do |form| %>
  <%= form.hidden_field(:business_id, value: @coupon.business_id) %>

  <%= render partial: 'coupon', locals: { f: form } %>

  <%= form.submit 'Add Coupon', class: 'btn btn-northcenter' %>
<% end %>

app/views/coupons/shared/coupon.html.erb
<div class="form-group">
  <%= label_tag(:name, 'Name') %>
  <%= f.text_field :name, class: 'form-control', placeholder: '$5 Off!', required: true %>
  <small id="nameHelp" class="form-text text-muted">Enter the featured coupon text</small>
</div>

<div class="form-group">
  <%= label_tag(:description, 'Description') %>
  <%= f.text_field :description, class: 'form-control', required: true %>
  <small id="descriptionHelp" class="form-text text-muted">Enter a more detailed description</small>
</div>

<div class="form-group">
  <%= label_tag(:start_date, 'Start Date') %>
  <%= f.date_field :start_date, class: 'form-control', required: true %>
  <small id="startDateHelp" class="form-text text-muted">When does the promotion start?</small>
</div>

<div class="form-group">
  <%= label_tag(:end_date, 'End Date') %>
  <%= f.date_field :end_date, class: 'form-control', required: true %>
  <small id="startDateHelp" class="form-text text-muted">When does the promotion end?</small>
</div>

<div class="form-group">
  <%= label_tag(:code, 'Code') %>
  <%= f.text_field :code, class: 'form-control' %>
  <small id="codeHelp" class="form-text text-muted">Code will be used to generate a bar code.</small>
</div>

app/views/coupons/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @coupon.name %></h5>
    <p class="card-text"><%= @coupon.description %></p>
    <div class="barcode-display"><%= @coupon.barcode_svg %></div>
    <div class="card-footer text-muted">
      Valid <%= @coupon.start_date %> - <%= @coupon.end_date %>
    </div>
    <div class="btn-group" role="group" aria-label="coupon buttons">
      <%= link_to 'Back', business_path(@coupon.business), class: 'btn btn-northcenter' %>
      <% if current_admin %>
        <%= link_to 'Edit Coupon', edit_coupon_path(@coupon), class: 'btn btn-warning' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Northcenter Coupons</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light">
      <span class="navbar-brand mb-0 h1">
        <%= link_to 'Northcenter Coupons', businesses_path %>
      </span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= form_tag '/search', method: :get, class: 'form-inline my-2 my-lg-0' do %>
              <%= text_field_tag :q, params[:q], required: true, class: 'form-control mr-sm-2', placeholder: 'Search by Business' %>
              <%= submit_tag 'Search', name: nil, class: 'btn btn-northcenter my-2 my-sm-0' %>
            <% end %>
          </li>
          <li class="nav-item active">
            <% if current_admin %>
              <%= link_to "Log out - #{current_admin.email}", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
              <%= link_to 'Add a New Business', new_business_path %>
            <% else %>
              <%= link_to 'Admin log in', new_admin_session_path, class: 'nav-link' %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <div class='container'>
      <% flash.each do |level, message| %>
        <div class="alert alert-<%= level %> alert-dismissible" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <nav class="navbar-expand-sm navbar fixed-bottom navbar-light">
      <%= link_to 'Northcenter Chamber of Commerce', "https://www.northcenterchamber.com/", target: :blank %>
    </nav>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>